apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: {{ include "customer360.name" . }}
    helm.sh/chart: {{ include "customer360.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}-pingconfig
spec:
  template:
    spec:
      containers:
      - env:
        - name: COLLECTIONS
          # collectionNames: {{ include "customer360.useCaseNames" . | trimSuffix " : " }}
          value: {{ include "customer360.useCaseUrls" . | trimSuffix "," }}
        image: pricecs/pingconfigurator:1.1
        imagePullPolicy: "Always"
        name: pingconfig
        resources: {}
        volumeMounts:
        - mountPath: /usr/src/app/postman_vars.json
          name: {{ .Release.Name }}-postman
          subPath: postman_vars.json
      restartPolicy: Never
      serviceAccountName: ""
      volumes:
      - configMap:
          items:
          - key: postman_vars.json
            path: postman_vars.json
          name: {{ .Release.Name }}-postman
        name: {{ .Release.Name }}-postman